### ISSUE TITLE
High perfomance Server using pond?

### ISSUE THREAD

**Issue by Vytek** [obsilp/rmnp#5]
Hi, I am very interesting create an open source high perfomance server using rmnp.

I have thought about using the pond library, but I am unable to integrate it properly. Do you have a skeleton or a prototype to recommend? A cordial greeting and I hope you will be able to answer me. This project is really cool!

https://github.com/alitto/pond

**Comment by tim-oster** [comment]
Hey, I think this depends on what you want to achieve. Part of rmnp's design is that is uses callback functions instead of channels because it spins up goroutines itself internally for every connection to allow processing multiple clients in parallel. If you look at `handleServerPacket` in `example/server.go`, that means that this callback function will be called concurrently whenever packets arrive and each handler can take as long as it wants to process the packets.

The design goal was to make it easy to implement server logic without worrying about goroutines and concurrency. Currently, I do not see the benefit of introducing the library you are suggesting. Can you elaborate on what you are hoping to gain from it?

**Comment by Vytek** [comment]
Thank you very much to answer! 

In light of what he said to me, I think I have completely misunderstood. I had hypothesized where to manage a pool capable of parallelizing the execution and interpretation of packets in the packet reception handle. But I don't have to do that because everything is already managed by the library (if I understand correctly ;-) My goal is to create a classic client-server architecture for a relay server to be used with Unity clients using your C # rmnp client implementation. The relay server will keep in memory a cmap (https://github.com/lrita/cmap) of all the connected clients and, according to the channel, it will send the relative payload to all or to the single client. For serialization I would like to use flatbuffers or messagepack so that they are quite optimized. I will publish the repo as soon as I reach stable code. Thanks again for everything!
